### ISSUE TITLE
Unable to Query Polymer on co.polymergenome.org/

### ISSUE THREAD

**Issue by gabrielsouza-oss** [Ramprasad-Group/bioplastic_design#2]
Chris, when trying to query a polymer at co.polymergenome.org, the website returns a "504 Gateway Time-out -
Server did not respond in time" error.
Could you gently check the availability of the server?

**Comment by kuelumbus** [comment]
Hi. Sorry for the late answer. I just saw your post now. This is resolved now. It was an issue with our server infrastructure.
